Team component
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #38
Opened 2020-10-31 20:12 UTC by gizemcdeniz

2020-11-02 07:45 UTC, bertacsevercan requested changes

2020-11-02 07:45 UTC, bertacsevercan commented on src/components/Team/index.css
> +  margin: 30px auto 50px;
All px needs to be changed to rem or em.

2020-11-02 07:45 UTC, bertacsevercan commented on src/components/Team/index.jsx
> +    <div className="App">
if you are not using this className App, consider deleting it or changing the name.

2020-11-03 09:35 UTC, halitbatur requested changes

2020-11-03 09:35 UTC, halitbatur commented on src/components/Team/Carousel.jsx
> +const teamMembers = [
let's move this data to a sperate file and import it from there

2020-11-03 09:35 UTC, halitbatur commented on src/components/Team/Carousel.jsx
> +import React from "react";
* this component should only have the Carousel and nothing else, any extra code should be moved to the Team component
* this component should be in a separate folder of it's own and the data it used should be coming form the parent as props and then used in it ( we do this so it can be reusable anywhere we want to use carousel in our project)

2020-11-05 08:14 UTC, bertacsevercan requested changes

2020-11-05 08:14 UTC, bertacsevercan commented on src/components/Team/Carousel.jsx
> +import "antd/dist/antd.css";
This antd  import is unnecessary, it's imported in App.js

2020-11-05 08:14 UTC, bertacsevercan commented on src/components/Team/Carousel.jsx
> +                    <InstagramOutlined href="#" /> {team.instagram}
Why do you have an href here and not in the others ?

2020-11-06 19:56 UTC, gizemmdeniz commented on src/components/Team/Carousel.jsx
> +                    <InstagramOutlined href="#" /> {team.instagram}
I will add your accounts later. Just added for trying now.

2020-11-08 09:11 UTC, bertacsevercan approved these changes
lgtm

2020-11-09 09:00 UTC, halitbatur requested changes

2020-11-09 09:00 UTC, halitbatur commented on src/components/Team/Carousel.jsx
> +const Carousel = (props) => {
there's no props gettings passed to this carousel so writing props here in uncessary

2020-11-09 09:00 UTC, halitbatur commented on src/components/Team/Carousel.jsx
> +import React from "react";
As I mentioned before 
* this component should be in a separate folder of it's own and the data it used should be coming form the parent as props (or imported from a data.js file) and then used in it ( we do this so it can be reusable anywhere we want to use carousel in our project)

2020-11-11 09:06 UTC, halitbatur approved these changes
only small change and its ready to be merged

2020-11-11 14:07 UTC, gizemcdeniz commented on src/components/Team/Carousel.jsx
> +import React from "react";
I moved the carousel to another file.

2020-11-11 14:21 UTC, halitbatur requested changes

2020-11-11 14:21 UTC, halitbatur commented on src/components/Team/index.jsx
> +import Carousel from "../TeamCarousel/index.jsx";
Component name should be changed to TeamCarousel

2020-11-13 09:12 UTC, halitbatur requested changes

2020-11-13 09:12 UTC, halitbatur commented on src/components/Team/index.jsx
> +import Carousel from "../TeamCarousel";
gizem this still says import Carousel ? could you please fix that to ```import TeamCarousel from '../TeamCarousel";```

2020-11-14 10:01 UTC, halitbatur approved these changes

2020-11-14 10:02 UTC, halitbatur commented
@gizemcdeniz still I cannot see route for the component could u add that ?

2020-11-14 10:03 UTC, merged