Dark mode theme
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #60
Opened 2020-11-21 02:26 UTC by cuygur

- day
![day](https://user-images.githubusercontent.com/54838188/99865154-e1f77580-2bb8-11eb-80a6-77fe16572dc6.jpg)

- night
![night](https://user-images.githubusercontent.com/54838188/99865150-de63ee80-2bb8-11eb-87b6-57c196b4b938.jpg)

- have error in the test

2020-11-21 12:26 UTC, bertacsevercan commented
I don't think a dark mode is necessary, we have to change a lot of things to make this happen.

2020-11-21 14:43 UTC, cuygur commented
@bertacsevercan you can respect my work. It's a very nice feature and it was a challenge. I did all. Only test left.

2020-11-21 14:53 UTC, bertacsevercan commented
@cuygur I do respect your work. I just meant this wasn't a priority, if you've finished it, we can use it.

2020-11-21 15:41 UTC, cuygur commented
@bertacsevercan okay thanks

2020-11-22 12:36 UTC, bertacsevercan approved these changes

2020-11-22 12:36 UTC, bertacsevercan commented
There are conflicts!

2020-11-22 12:46 UTC, bertacsevercan requested changes

2020-11-22 12:46 UTC, bertacsevercan commented on src/components/NavBar/index.jsx
> +              <Menu.Item key="9" className="navbarLogout">
This key should be 12

2020-11-22 12:46 UTC, bertacsevercan commented on src/components/NavBar/index.jsx
> +            <Menu.Item key="8" className="navbarAdmin">
This key should be 11

2020-11-22 17:46 UTC, cuygur commented
after the second merge I couldn't pass test..

2020-11-25 12:33 UTC, closed without merging