Team comp fix
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #63
Opened 2020-11-21 14:32 UTC by gizemcdeniz

Desktop
![image](https://user-images.githubusercontent.com/61707093/99879651-4816e380-2c1f-11eb-9787-53938b2467f0.png)
![image](https://user-images.githubusercontent.com/61707093/99879659-4e0cc480-2c1f-11eb-8954-3b3458e9d9de.png)

Mobile
![image](https://user-images.githubusercontent.com/61707093/99879685-6a106600-2c1f-11eb-8440-9d879d6c19d7.png)

Ipad
![image](https://user-images.githubusercontent.com/61707093/99879692-75fc2800-2c1f-11eb-81de-ce25457311a9.png)

2020-11-21 14:40 UTC, bertacsevercan requested changes
Looks good but you need to create this branch from the dev branch. I think you created this from previous team branch, so that is why it has all the previous commits.

2020-11-21 14:40 UTC, bertacsevercan commented on src/locales/en/translation.json
> +      "gizemdescription": "Junior Engineer",
Maybe add "Software" into these.

2020-11-22 20:50 UTC, halitbatur requested changes

2020-11-22 20:50 UTC, halitbatur commented on src/components/TeamCarousel/carousel.css
> +}
new line

2020-11-23 14:26 UTC, bertacsevercan approved these changes

2020-11-23 16:00 UTC, halitbatur approved these changes

2020-11-23 16:04 UTC, merged