Fix-adminpage-padding
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #64
Opened 2020-11-21 14:35 UTC by bertacsevercan

- Add the same paddings to wrapper divs in the Admin page.

2020-11-21 15:46 UTC, halitbatur requested changes

2020-11-21 15:46 UTC, halitbatur commented on src/components/CouponsChart/style.css
> +}
new line

2020-11-21 15:46 UTC, halitbatur commented on src/components/CreateCoupons/style.css
> -.coupons {
new line

2020-11-22 09:34 UTC, halitbatur approved these changes
fix conflicts and its ready to be merged

2020-11-22 11:04 UTC, ihab-sensei approved these changes
Looks good!

2020-11-22 14:41 UTC, merged