Fix youcanhelp
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #66
Opened 2020-11-21 19:05 UTC by gizemcdeniz

Desktop
![image](https://user-images.githubusercontent.com/61707093/99885323-0bf67980-2c45-11eb-8270-6bc5190565f2.png)

Ipad
![image](https://user-images.githubusercontent.com/61707093/99885336-20d30d00-2c45-11eb-9b2b-f2f898773e21.png)

Mobile
![image](https://user-images.githubusercontent.com/61707093/99885397-a0f97280-2c45-11eb-8bef-0e3aca0e2f1c.png)

2020-11-21 23:46 UTC, cuygur commented on src/components/YouCanHelp/index.jsx
>            />
New line need before export at line 50

2020-11-21 23:47 UTC, cuygur requested changes
in HD size(1280x800) I see like this. Hiding text can be solution. We need to discuss 

![Screenshot 2020-11-22 023602](https://user-images.githubusercontent.com/54838188/99889986-a5388680-2c6b-11eb-9d81-d103341728e4.jpg)


Please check below image;
![image](https://user-images.githubusercontent.com/61707093/99903612-773c5c00-2cd6-11eb-9dd4-30a06caae5d6.png)

2020-11-22 17:12 UTC, halitbatur approved these changes

2020-11-22 21:03 UTC, bertacsevercan approved these changes

2020-11-22 23:07 UTC, cuygur commented
Very strange. I don't see like that. It's very important, Ihab will demo and his screen is HD. @ihab-sensei how do you see ?

2020-11-23 10:12 UTC, cuygur commented
We solved the problem. Now it's perfect. Good job!

2020-11-23 10:14 UTC, cuygur approved these changes
Well done

2020-11-23 10:38 UTC, merged