Fix-logout
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #68
Opened 2020-11-21 20:53 UTC by bertacsevercan

- Add a logout function to the logout button.
- This will have conflicts with the #67 pr, because this or includes that one. So after #67 is merged, I will resolve those conflicts for this one.

2020-11-21 23:23 UTC, cuygur approved these changes

2020-11-22 10:23 UTC, bertacsevercan commented
Solved conflicts. Ready to be merged! PTAL! @halitbatur

2020-11-22 12:54 UTC, halitbatur requested changes

2020-11-22 12:54 UTC, halitbatur commented on src/components/LogOut/index.jsx
> +const LogOut = ({ setUserExist }) => {
can we change this to Logout since it's one word, same thing with DirName

2020-11-22 12:54 UTC, halitbatur commented on src/components/LogOut/index.jsx
> +        visible={modalVisible}
we can directly use the setstates here instead of nesting it in another function

2020-11-22 12:54 UTC, halitbatur commented on src/components/LogOut/index.jsx
> +        onCancel={handleCancel}
same thing here with the nesting

2020-11-22 14:12 UTC, halitbatur approved these changes
remove these lines and its ready to be merged

2020-11-22 14:12 UTC, halitbatur commented on src/components/Signout/style.css
> +
extra 3 lines here

2020-11-22 15:41 UTC, merged