Fix navbarsec
ReCoded-Org/capstone-istanbul-feed_the_needy pull request #92
Opened 2020-11-23 20:11 UTC by gizemcdeniz

Before Login Ipad:
![image](https://user-images.githubusercontent.com/61707093/100010142-df776480-2de0-11eb-911f-a5b34d31f3e8.png)

Before Login Ipad Pro:
![image](https://user-images.githubusercontent.com/61707093/100010270-0e8dd600-2de1-11eb-90df-46b461b55d53.png)

Before Login Mobile:
![image](https://user-images.githubusercontent.com/61707093/100010240-02a21400-2de1-11eb-9f05-73a8fced72ff.png)
![image](https://user-images.githubusercontent.com/61707093/100010333-2bc2a480-2de1-11eb-97be-20be21e3c1a1.png)

After Login Ipad:
![image](https://user-images.githubusercontent.com/61707093/100009992-a9d27b80-2de0-11eb-9334-fadbb52aed9f.png)

After Login Ipad Pro:
![image](https://user-images.githubusercontent.com/61707093/100010072-c5d61d00-2de0-11eb-823f-20f08fd50935.png)

After Login Mobile:
![image](https://user-images.githubusercontent.com/61707093/100010035-bbb41e80-2de0-11eb-8e2f-f4b4f89721c7.png)

2020-11-23 20:57 UTC, bertacsevercan approved these changes

2020-11-23 21:27 UTC, cuygur approved these changes

2020-11-24 09:32 UTC, halitbatur requested changes

2020-11-24 09:32 UTC, halitbatur commented on src/components/NavBar/style.css
> +  }
new line

2020-11-24 11:43 UTC, halitbatur approved these changes

2020-11-24 11:44 UTC, merged